"use client";

import React from 'react';
import { Button } from '@/components/ui/button';
import { FileDown, Printer } from 'lucide-react';
import { DiaryEvent, groupEventsByDate, getEventTypeLabel } from '@/lib/diary-utils';
import { Grow } from '@/lib/db';

interface DiaryPdfExportProps {
  grow: Grow;
  events: DiaryEvent[];
}

const DiaryPdfExport: React.FC<DiaryPdfExportProps> = ({ grow, events }) => {

  const handlePrint = () => {
    const printContent = generatePrintContent();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
      }, 250);
    }
  };

  const handleExportText = () => {
    const textContent = generateTextExport();
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${grow.name.replace(/[^a-z0-9]/gi, '_')}_diary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateTextExport = (): string => {
    const lines: string[] = [];
    lines.push('='.repeat(60));
    lines.push(`GROW DIARY: ${grow.name}`);
    lines.push('='.repeat(60));
    lines.push('');
    lines.push(`Started: ${new Date(grow.startDate).toLocaleDateString()}`);
    lines.push(`Current Phase: ${grow.currentPhase}`);
    lines.push(`Total Events: ${events.length}`);
    lines.push('');
    lines.push('-'.repeat(60));
    lines.push('TIMELINE');
    lines.push('-'.repeat(60));
    lines.push('');

    const grouped = groupEventsByDate(events);
    const sortedDates = Array.from(grouped.keys()).sort(
      (a, b) => new Date(b).getTime() - new Date(a).getTime()
    );

    sortedDates.forEach(dateKey => {
      const dayEvents = grouped.get(dateKey) || [];
      lines.push(`📅 ${new Date(dateKey).toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}`);
      lines.push('');
      
      dayEvents.forEach(event => {
        lines.push(`  ${event.icon} ${event.title}`);
        if (event.plantName) {
          lines.push(`     Plant: ${event.plantName}`);
        }
        lines.push(`     ${event.description}`);
        lines.push('');
      });
    });

    lines.push('');
    lines.push('='.repeat(60));
    lines.push(`Generated by GrowPanion on ${new Date().toLocaleString()}`);
    lines.push('='.repeat(60));

    return lines.join('\n');
  };

  const generatePrintContent = (): string => {
    const grouped = groupEventsByDate(events);
    const sortedDates = Array.from(grouped.keys()).sort(
      (a, b) => new Date(b).getTime() - new Date(a).getTime()
    );

    const eventRows = sortedDates.map(dateKey => {
      const dayEvents = grouped.get(dateKey) || [];
      const formattedDate = new Date(dateKey).toLocaleDateString('en-US', {
        weekday: 'short',
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });

      return `
        <tr>
          <td colspan="4" style="background: #f3f4f6; padding: 8px; font-weight: bold; border-top: 2px solid #ccc;">
            📅 ${formattedDate}
          </td>
        </tr>
        ${dayEvents.map(event => `
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${event.icon}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">
              <strong>${event.title}</strong>
              ${event.plantName ? `<br><small style="color: #666;">🌿 ${event.plantName}</small>` : ''}
            </td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${event.description}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; color: #666; font-size: 12px;">
              ${getEventTypeLabel(event.type)}
            </td>
          </tr>
        `).join('')}
      `;
    }).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Grow Diary - ${grow.name}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
          }
          h1 { color: #16a34a; margin-bottom: 5px; }
          .meta { color: #666; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { 
            background: #16a34a; 
            color: white; 
            padding: 10px; 
            text-align: left;
          }
          .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ccc;
            text-align: center;
            color: #666;
            font-size: 12px;
          }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <h1>🌿 ${grow.name}</h1>
        <div class="meta">
          <p><strong>Started:</strong> ${new Date(grow.startDate).toLocaleDateString()}</p>
          <p><strong>Current Phase:</strong> ${grow.currentPhase}</p>
          <p><strong>Total Events:</strong> ${events.length}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th style="width: 40px;"></th>
              <th>Event</th>
              <th>Details</th>
              <th style="width: 100px;">Type</th>
            </tr>
          </thead>
          <tbody>
            ${eventRows}
          </tbody>
        </table>

        <div class="footer">
          <p>Generated by GrowPanion on ${new Date().toLocaleString()}</p>
        </div>
      </body>
      </html>
    `;
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handlePrint}
        className="bg-gray-800 border-gray-700 hover:bg-gray-700 text-white"
      >
        <Printer className="h-4 w-4 mr-2" />
        Print
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleExportText}
        className="bg-gray-800 border-gray-700 hover:bg-gray-700 text-white"
      >
        <FileDown className="h-4 w-4 mr-2" />
        Export
      </Button>
    </div>
  );
};

DiaryPdfExport.displayName = 'DiaryPdfExport';

export default DiaryPdfExport;
