import type { Genetics, LineageEdge } from '@/lib/db';

/**
 * Curated, hand-verified default genetics for the most well-known cannabis cultivars.
 *
 * Data points (type, flowering time, THC range, dominant terpenes and lineage) were
 * compiled from widely cited public strain references (e.g. Leafly, Strainpedia,
 * SeedFinder, breeder catalogues). Numbers reflect commonly reported ranges and are
 * meant as sensible defaults, not lab-exact values. Lineage edges only connect
 * cultivars that also exist as nodes in this set so the lineage graph stays consistent.
 */

export const CURATED_SEED_VERSION = '2026.06.26-curated-famous-v2';

const SEED_TIMESTAMP = '2026-06-26T00:00:00.000Z';

type CuratedGeneticsInput = Omit<Genetics, 'id' | 'source' | 'createdAt' | 'updatedAt'> & {
  /** Short slug; the stored id is prefixed with `gp-`. */
  key: string;
};

function buildGenetics(input: CuratedGeneticsInput): Genetics {
  const { key, ...rest } = input;
  return {
    id: `gp-${key}`,
    ...rest,
    source: 'default',
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  };
}

/**
 * Creates a lineage edge between two curated cultivars referenced by their short keys.
 * Edge ids use the `edge:` prefix so they are recognised and refreshed on re-import.
 */
function buildEdge(
  parentKey: string,
  childKey: string,
  relationType: LineageEdge['relationType'] = 'parent',
): LineageEdge {
  return {
    id: `edge:${parentKey}->${childKey}`,
    parentGeneticsId: `gp-${parentKey}`,
    childGeneticsId: `gp-${childKey}`,
    relationType,
    createdAt: SEED_TIMESTAMP,
  };
}

const CURATED_GENETICS_INPUT: CuratedGeneticsInput[] = [
  // ---- Landraces & foundational classics ----
  {
    key: 'afghani',
    name: 'Afghani',
    breeder: 'Landrace',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Afghanistan landrace (Hindu Kush region)',
    notes: 'Pure indica landrace prized for heavy resin; genetic backbone of countless modern hybrids.',
  },
  {
    key: 'thai',
    name: 'Thai',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 13,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Limonene'],
    cannabinoids: 'THC 12-18%',
    origin: 'Thailand landrace sativa',
    notes: 'Classic tropical sativa landrace with long flowering and soaring cerebral effect.',
  },
  {
    key: 'hindu-kush',
    name: 'Hindu Kush',
    breeder: 'Landrace',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Limonene'],
    cannabinoids: 'THC 16-20%',
    origin: 'Afghanistan / Pakistan mountain landrace',
    notes: 'Resin-heavy pure indica landrace; a parent of OG Kush.',
  },
  {
    key: 'durban-poison',
    name: 'Durban Poison',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 8,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 15-25%',
    origin: 'South African landrace sativa',
    notes: 'Energetic, anise-sweet landrace; the sativa half of Girl Scout Cookies.',
  },
  {
    key: 'hawaiian',
    name: 'Hawaiian',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Pinene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Hawaiian island landrace sativa',
    notes: 'Tropical, fruity sativa landrace; parent of Pineapple Express.',
  },
  {
    key: 'colombian-gold',
    name: 'Colombian Gold',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Terpinolene'],
    cannabinoids: 'THC 14-20%',
    origin: 'Santa Marta, Colombia landrace',
    notes: 'Legendary uplifting landrace; a building block of Skunk #1.',
  },
  {
    key: 'acapulco-gold',
    name: 'Acapulco Gold',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 15-21%',
    origin: 'Acapulco, Mexico landrace',
    notes: 'Classic Mexican landrace sativa; contributor to Skunk #1.',
  },
  {
    key: 'haze',
    name: 'Haze',
    breeder: 'Original Haze Brothers',
    type: 'Sativa',
    floweringWeeks: 13,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Colombian x Mexican x Thai x South Indian',
    notes: 'The foundational sativa hybrid behind the entire Haze family.',
  },
  {
    key: 'skunk-1',
    name: 'Skunk #1',
    breeder: 'Sacred Seed Co. / Sensi Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 15-19%',
    origin: 'Afghani x Acapulco Gold x Colombian Gold',
    notes: 'First truly stabilized hybrid; one of the three pillars of modern breeding.',
  },
  {
    key: 'northern-lights',
    name: 'Northern Lights',
    breeder: 'Sensi Seeds',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Pinene'],
    cannabinoids: 'THC 16-21%',
    origin: 'Afghani x Thai',
    notes: 'Near-pure indica benchmark; fast, resinous and forgiving to grow.',
  },
  {
    key: 'super-skunk',
    name: 'Super Skunk',
    breeder: 'Sensi Seeds',
    type: 'Hybrid',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 16-19%',
    origin: 'Skunk #1 x Afghani',
    notes: 'Skunk #1 backcrossed to Afghani for more resin and pungency; parent of Sour Diesel.',
  },
  {
    key: 'shiva-skunk',
    name: 'Shiva Skunk',
    breeder: 'Sensi Seeds',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Northern Lights #5 x Skunk #1',
    notes: 'Resinous indica-dominant cross; part of the Jack Herer recipe.',
  },
  {
    key: 'big-bud',
    name: 'Big Bud',
    breeder: 'Sensi Seeds',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Limonene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Northern Lights x Skunk #1 x Afghani',
    notes: 'Famous for enormous yields and dense buds; parent of Granddaddy Purple.',
  },
  {
    key: 'blueberry',
    name: 'Blueberry',
    breeder: 'DJ Short',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 16-20%',
    origin: 'Purple Thai x Afghani',
    notes: 'DJ Short classic with sweet berry aroma; the indica side of Blue Dream.',
  },
  {
    key: 'super-silver-haze',
    name: 'Super Silver Haze',
    breeder: 'Green House Seeds',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-23%',
    origin: 'Haze x Northern Lights x Skunk #1',
    notes: 'Multi Cannabis Cup winning sativa combining Haze with resin-heavy classics.',
  },
  {
    key: 'jack-herer',
    name: 'Jack Herer',
    breeder: 'Sensi Seeds',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Haze x Northern Lights #5 x Shiva Skunk',
    notes: 'Spicy-pine sativa named after the cannabis activist; an enduring Dutch classic.',
  },
  {
    key: 'white-widow',
    name: 'White Widow',
    breeder: 'Green House Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Pinene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Brazilian Sativa x South Indian Indica',
    notes: 'Frosty balanced hybrid; one of the first globally famous Dutch strains.',
  },

  // ---- Chem / Diesel / OG family ----
  {
    key: 'chemdawg',
    name: 'Chemdawg',
    breeder: 'Clone-only (Chemdog)',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Unknown (1991 bagseed)',
    notes: 'Pungent diesel cut of mysterious origin; ancestor of OG Kush and Sour Diesel.',
  },
  {
    key: 'og-kush',
    name: 'OG Kush',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 19-26%',
    origin: 'Chemdawg x Hindu Kush x Lemon Thai',
    notes: 'The West Coast cornerstone; lemon-pine-fuel aroma and parent of countless modern strains.',
  },
  {
    key: 'sour-diesel',
    name: 'Sour Diesel',
    breeder: 'Clone-only (NYC)',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 19-26%',
    origin: 'Chemdawg 91 x Super Skunk',
    notes: 'Fast, energizing fuel-forward sativa born from the NYC underground scene.',
  },
  {
    key: 'chems-sister',
    name: "Chem's Sister",
    breeder: 'Clone-only',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Chemdawg phenotype',
    notes: 'Sativa-leaning Chemdawg selection; a parent of Original Glue (GG4).',
  },
  {
    key: 'sour-dubble',
    name: 'Sour Dubble',
    breeder: 'Apothecary Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Sour Diesel x Sour Bubble',
    notes: 'Sweet-and-sour diesel hybrid; a parent of Original Glue (GG4).',
  },
  {
    key: 'chocolate-diesel',
    name: 'Chocolate Diesel',
    breeder: 'Connoisseur Genetics',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Chocolate Thai x Sour Diesel',
    notes: 'Coffee-and-fuel sativa contributing the chocolate note to Original Glue (GG4).',
  },
  {
    key: 'original-glue',
    name: 'Original Glue (GG4)',
    breeder: 'GG Strains',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    cannabinoids: 'THC 24-30%',
    origin: "Chem's Sister x Sour Dubble x Chocolate Diesel",
    notes: 'Award-winning, extremely resinous hybrid; a happy accident turned modern legend.',
  },
  {
    key: 'triangle-kush',
    name: 'Triangle Kush',
    breeder: 'Clone-only (Florida)',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 20-26%',
    origin: 'OG Kush phenotype (Florida)',
    notes: 'Gassy Florida OG cut; the potency backbone of Wedding Cake.',
  },
  {
    key: 'face-off-og',
    name: 'Face Off OG',
    breeder: 'Archive Seed Bank',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-28%',
    origin: 'OG Kush phenotype',
    notes: 'Heavy, fuel-forward OG cut; the father of Do-Si-Dos.',
  },
  {
    key: 'bubba-kush',
    name: 'Bubba Kush',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    cannabinoids: 'THC 15-22%',
    origin: 'OG Kush x Unknown Indica',
    notes: 'Coffee-and-cocoa indica delivering a heavy, sedating body stone.',
  },
  {
    key: 'bruce-banner',
    name: 'Bruce Banner',
    breeder: 'Dark Horse Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 24-29%',
    origin: 'OG Kush x Strawberry Diesel',
    notes: 'Explosively potent, fast-acting sativa-leaning hybrid with sweet diesel aroma.',
  },
  {
    key: 'larry-og',
    name: 'Larry OG',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush x SFV OG Kush',
    notes: 'Citrus-fuel OG cut; a parent of Purple Punch.',
  },

  // ---- Cookies / Dessert family ----
  {
    key: 'gsc',
    name: 'GSC (Girl Scout Cookies)',
    breeder: 'Cookie Fam',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 22-28%',
    origin: 'OG Kush x Durban Poison',
    notes: 'The strain that launched the Cookies empire; sweet, minty and extremely influential.',
  },
  {
    key: 'thin-mint-gsc',
    name: 'Thin Mint GSC',
    breeder: 'Cookie Fam',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 22-28%',
    origin: 'GSC phenotype',
    notes: 'Mint-chocolate, indica-leaning GSC cut; a parent of Gelato.',
  },
  {
    key: 'animal-cookies',
    name: 'Animal Cookies',
    breeder: 'Seed Junky Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-27%',
    origin: 'GSC x Fire OG',
    notes: 'Dense, sweet-and-sour Cookies descendant; a parent of Animal Mints.',
  },
  {
    key: 'animal-mints',
    name: 'Animal Mints',
    breeder: 'Seed Junky Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 22-28%',
    origin: 'Animal Cookies x SinMint Cookies',
    notes: 'Creamy, minty Cookies cross delivering the vanilla note to Wedding Cake.',
  },
  {
    key: 'sunset-sherbet',
    name: 'Sunset Sherbet',
    breeder: 'Sherbinski',
    type: 'Hybrid',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 18-24%',
    origin: 'GSC x Pink Panties',
    notes: 'Creamy, fruity GSC descendant; a parent of Gelato.',
  },
  {
    key: 'gelato',
    name: 'Gelato',
    breeder: 'Cookie Fam / Sherbinski',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 17-25%',
    origin: 'Sunset Sherbet x Thin Mint GSC',
    notes: 'Dessert-forward benchmark hybrid and one of the most copied strains of the decade.',
  },
  {
    key: 'gelato-33',
    name: 'Gelato #33 (Larry Bird)',
    breeder: 'Cookie Fam',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Gelato phenotype',
    notes: 'The most celebrated Gelato cut; a parent of Runtz.',
  },
  {
    key: 'wedding-cake',
    name: 'Wedding Cake',
    breeder: 'Seed Junky Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Triangle Kush x Animal Mints',
    notes: 'Vanilla-cream, pepper and gas; Leafly Strain of the Year 2019.',
  },
  {
    key: 'do-si-dos',
    name: 'Do-Si-Dos',
    breeder: 'Archive Seed Bank',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Linalool'],
    cannabinoids: 'THC 22-30%',
    origin: 'GSC (OGKB) x Face Off OG',
    notes: 'Floral, gassy, very potent indica-dominant Cookies cross for the evening.',
  },

  // ---- Zkittlez / Runtz / Fruit family ----
  {
    key: 'grape-ape',
    name: 'Grape Ape',
    breeder: 'Apothecary Genetics',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 15-23%',
    origin: 'Mendocino Purps x Skunk #1 x Afghani',
    notes: 'Grape-candy indica with deep purple hues; a parent of Zkittlez.',
  },
  {
    key: 'grapefruit',
    name: 'Grapefruit',
    breeder: 'Nirvana Seeds',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene'],
    cannabinoids: 'THC 15-22%',
    origin: 'Cinderella 99 lineage',
    notes: 'Bright citrus sativa; a parent of Zkittlez.',
  },
  {
    key: 'zkittlez',
    name: 'Zkittlez',
    breeder: 'Dying Breed / 3rd Gen / Terp Hogz',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Humulene'],
    cannabinoids: 'THC 18-23%',
    origin: 'Grape Ape x Grapefruit',
    notes: 'Candy-sweet, tropical-fruit indica; a parent of Runtz.',
  },
  {
    key: 'runtz',
    name: 'Runtz',
    breeder: 'Cookies / Runtz Crew',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 19-29%',
    origin: 'Zkittlez x Gelato',
    notes: 'Candy-fruit-cream exotic that defined strain-as-lifestyle branding.',
  },

  // ---- Purple family ----
  {
    key: 'purple-urkle',
    name: 'Purple Urkle',
    breeder: 'Clone-only (Mendocino)',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Linalool'],
    cannabinoids: 'THC 16-20%',
    origin: 'Mendocino Purps phenotype',
    notes: 'Deep grape-berry indica; the colour and aroma source for Granddaddy Purple.',
  },
  {
    key: 'granddaddy-purple',
    name: 'Granddaddy Purple',
    breeder: 'Ken Estes',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 17-23%',
    origin: 'Purple Urkle x Big Bud',
    notes: 'Iconic purple indica with grape-berry aroma and heavy body sedation.',
  },
  {
    key: 'purple-punch',
    name: 'Purple Punch',
    breeder: 'Supernova Gardens',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Pinene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Larry OG x Granddaddy Purple',
    notes: 'Dessert indica with grape-candy and blueberry-muffin aroma.',
  },

  // ---- Haze / Sativa hybrids ----
  {
    key: 'blue-dream',
    name: 'Blue Dream',
    breeder: 'Clone-only (Santa Cruz)',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 17-24%',
    origin: 'Blueberry x Haze',
    notes: 'Smooth berry sativa-leaning hybrid; a long-running dispensary staple.',
  },
  {
    key: 'trainwreck',
    name: 'Trainwreck',
    breeder: 'Clone-only (NorCal)',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Myrcene', 'Pinene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Mexican x Thai x Afghani',
    notes: 'Hard-hitting, lemon-pine sativa hybrid; a parent of Pineapple Express.',
  },
  {
    key: 'pineapple-express',
    name: 'Pineapple Express',
    breeder: 'G13 Labs',
    type: 'Hybrid',
    floweringWeeks: 8,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Pinene'],
    cannabinoids: 'THC 19-25%',
    origin: 'Trainwreck x Hawaiian',
    notes: 'Tropical, energetic sativa-dominant hybrid popularized by the 2008 film.',
  },
  {
    key: 'green-crack',
    name: 'Green Crack',
    breeder: 'Clone-only',
    type: 'Sativa',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 15-21%',
    origin: 'Skunk #1 phenotype',
    notes: 'Sharp, mango-citrus daytime sativa selected from Skunk #1.',
  },
  {
    key: 'ak-47',
    name: 'AK-47',
    breeder: 'Serious Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Pinene'],
    cannabinoids: 'THC 16-20%',
    origin: 'Colombian x Mexican x Thai x Afghani',
    notes: 'Award-winning, mellow-yet-cerebral hybrid blending four classic landraces.',
  },

  // ---- Additional landraces & heirloom roots ----
  {
    key: 'mexican',
    name: 'Mexican',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Pinene', 'Terpinolene'],
    cannabinoids: 'THC 12-18%',
    origin: 'Mexican landrace sativa',
    notes: 'Classic Central American landrace; a building block of Skunk, Haze and Trainwreck.',
  },
  {
    key: 'chocolate-thai',
    name: 'Chocolate Thai',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 13,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Humulene'],
    cannabinoids: 'THC 12-16%',
    origin: 'Thailand landrace sativa',
    notes: 'Rare cocoa-scented Thai heirloom; parent of Chocolate Diesel and Chocolope.',
  },
  {
    key: 'purple-thai',
    name: 'Purple Thai',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 12,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Myrcene'],
    cannabinoids: 'THC 14-18%',
    origin: 'Highland Oaxacan x Thai',
    notes: 'Heirloom sativa; the sativa half of DJ Short Blueberry and Flo.',
  },
  {
    key: 'mazar',
    name: 'Mazar-I-Sharif',
    breeder: 'Landrace',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Northern Afghanistan landrace',
    notes: 'Heavy resin Afghan landrace; a parent of Skywalker.',
  },
  {
    key: 'malawi',
    name: 'Malawi Gold',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 14,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Limonene'],
    cannabinoids: 'THC 16-22%',
    origin: 'Malawi landrace sativa',
    notes: 'Long-flowering African heirloom famous for soaring, energetic effects.',
  },
  {
    key: 'panama-red',
    name: 'Panama Red',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 12,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Pinene'],
    cannabinoids: 'THC 13-19%',
    origin: 'Panama landrace sativa',
    notes: '1960s-70s legend; a pure tropical sativa with a clear, racy high.',
  },
  {
    key: 'lambsbread',
    name: 'Lamb\u2019s Bread',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 16-21%',
    origin: 'Jamaican landrace sativa',
    notes: 'Jamaican heirloom (a.k.a. Lamb\u2019s Breath) prized for its uplifting buzz.',
  },
  {
    key: 'swazi-gold',
    name: 'Swazi Gold',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 13,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Pinene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Eswatini (Swaziland) landrace sativa',
    notes: 'Hardy African heirloom with citrus-incense aroma and energetic effect.',
  },
  {
    key: 'nepalese',
    name: 'Nepalese',
    breeder: 'Landrace',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Humulene'],
    cannabinoids: 'THC 14-18%',
    origin: 'Himalayan (Nepal) landrace',
    notes: 'Hashplant heirloom from the Himalayas; warm, earthy and resinous.',
  },
  {
    key: 'ruderalis',
    name: 'Cannabis Ruderalis',
    breeder: 'Landrace',
    type: 'Indica',
    floweringWeeks: 7,
    stretch: 'Low',
    terpeneProfile: ['Myrcene'],
    cannabinoids: 'THC 1-5%',
    origin: 'Central Asian / Russian ruderalis',
    notes: 'Auto-flowering wild type; the genetic basis of all modern autoflower hybrids.',
  },
  {
    key: 'g13',
    name: 'G13',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 20-24%',
    origin: 'Legendary clone-only Afghani selection',
    notes: 'Mythologized government-grade indica; a parent of G13 Haze and MK Ultra.',
  },
  {
    key: 'california-orange',
    name: 'California Orange',
    breeder: 'Heirloom',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene'],
    cannabinoids: 'THC 14-20%',
    origin: '1980s California heirloom',
    notes: 'Sweet citrus classic (a.k.a. Cali-O); the orange half of Tangie.',
  },
  {
    key: 'cannalope-haze',
    name: 'Cannalope Haze',
    breeder: 'DNA Genetics',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Terpinolene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Mexican Haze x Original Haze',
    notes: 'Melon-sweet fast Haze; the sativa half of Chocolope.',
  },

  // ---- OG / Kush dynasty expansion ----
  {
    key: 'sfv-og',
    name: 'SFV OG',
    breeder: 'Cali Connection',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush phenotype (San Fernando Valley)',
    notes: 'Lemon-pine OG cut from the SFV; a parent of Larry OG, Tahoe OG and Fire OG.',
  },
  {
    key: 'fire-og',
    name: 'Fire OG',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush x SFV OG Kush',
    notes: 'One of the most potent OG cuts; a parent of Animal Cookies and White Fire OG.',
  },
  {
    key: 'tahoe-og',
    name: 'Tahoe OG',
    breeder: 'Cali Connection',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush x SFV OG',
    notes: 'Fast-hitting, heavy OG cut beloved for relaxation; a parent of FPOG.',
  },
  {
    key: 'ghost-og',
    name: 'Ghost OG',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'OG Kush phenotype',
    notes: 'Ethereal, citrus-fuel OG cut; a parent of Ghost Train Haze and Banana Kush.',
  },
  {
    key: 'skywalker',
    name: 'Skywalker',
    breeder: 'Dutch Passion',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Mazar x Blueberry',
    notes: 'Sweet, spacey indica; crossed with OG Kush to make Skywalker OG.',
  },
  {
    key: 'skywalker-og',
    name: 'Skywalker OG',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Skywalker x OG Kush',
    notes: 'Spicy, fruity OG-leaning indica with a strong, sedating body effect.',
  },
  {
    key: 'headband',
    name: 'Headband',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush x Sour Diesel',
    notes: 'Diesel-citrus hybrid named for the pressure it leaves around the head.',
  },
  {
    key: 'gmo',
    name: 'GMO (Garlic Cookies)',
    breeder: 'Mamiko / Divine Genetics',
    type: 'Indica',
    floweringWeeks: 10,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 24-30%',
    origin: 'Chemdawg x GSC',
    notes: 'Savory garlic-and-funk powerhouse; a foundational modern breeding strain.',
  },
  {
    key: 'master-kush',
    name: 'Master Kush',
    breeder: 'White Label / Dutch',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Limonene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Hindu Kush x Skunk #1',
    notes: 'Earthy, citrus Amsterdam classic; relaxing without heavy sedation.',
  },
  {
    key: 'alien-og',
    name: 'Alien OG',
    breeder: 'Cali Connection',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 20-28%',
    origin: 'Tahoe OG x Alien Kush',
    notes: 'Lemon-pine OG hybrid with a notably strong, psychedelic-leaning high.',
  },
  {
    key: 'king-louis',
    name: 'King Louis XIII',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Pinene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush phenotype',
    notes: 'Intensely piney, gassy OG indica with a deeply relaxing finish.',
  },
  {
    key: 'khalifa-kush',
    name: 'Khalifa Kush',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 22-29%',
    origin: 'OG Kush phenotype',
    notes: 'Wiz Khalifa\u2019s signature OG cut; sharp lemon-pine and very potent.',
  },
  {
    key: 'platinum-og',
    name: 'Platinum OG',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-24%',
    origin: 'OG Kush x Master Kush x ...',
    notes: 'Frosty, heavy three-way OG indica known for its silvery sheen.',
  },
  {
    key: 'mk-ultra',
    name: 'MK Ultra',
    breeder: 'T.H.Seeds',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-23%',
    origin: 'G13 x OG Kush',
    notes: 'Hypnotically strong indica; a parent of CBD line Cannatonic.',
  },
  {
    key: 'g13-haze',
    name: 'G13 Haze',
    breeder: 'Barneys Farm',
    type: 'Hybrid',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Myrcene'],
    cannabinoids: 'THC 20-24%',
    origin: 'G13 x Haze',
    notes: 'Cannabis Cup winning Haze hybrid pairing G13 resin with soaring sativa.',
  },
  {
    key: 'kosher-kush',
    name: 'Kosher Kush',
    breeder: 'DNA Genetics',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 22-29%',
    origin: 'OG Kush phenotype',
    notes: 'Award-winning, earthy-fruity OG indica with a heavy, relaxing punch.',
  },
  {
    key: 'mendo-breath',
    name: 'Mendo Breath',
    breeder: 'Gage Green Genetics',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 19-24%',
    origin: 'OG Kush Breath x Mendo Montage',
    notes: 'Caramel-vanilla OG indica; a parent of Peanut Butter Breath.',
  },
  {
    key: 'banana-kush',
    name: 'Banana Kush',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Ghost OG x Skunk Haze',
    notes: 'Creamy banana aroma; a relaxed, dreamy West Coast favourite.',
  },
  {
    key: 'banana-og',
    name: 'Banana OG',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 20-25%',
    origin: 'OG Kush x Banana',
    notes: 'Sweet, overripe-banana OG indica that creeps up with heavy effects.',
  },

  // ---- Diesel / Chem expansion ----
  {
    key: 'nyc-diesel',
    name: 'NYC Diesel',
    breeder: 'Soma Seeds',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-21%',
    origin: 'Mexican x Afghani',
    notes: 'Grapefruit-diesel sativa classic; a parent of Strawberry Diesel.',
  },
  {
    key: 'strawberry-cough',
    name: 'Strawberry Cough',
    breeder: 'Kyle Kushman',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Strawberry Fields x Haze',
    notes: 'Sweet strawberry sativa with an uplifting, talkative buzz.',
  },
  {
    key: 'strawberry-diesel',
    name: 'Strawberry Diesel',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Strawberry Cough x NYC Diesel',
    notes: 'Sweet-fuel hybrid; the high-energy half of Bruce Banner.',
  },
  {
    key: 'tres-dawg',
    name: 'Tres Dawg',
    breeder: 'Top Dawg Seeds',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Chemdawg x Afghani #1',
    notes: 'Stabilized Chem backcross; a parent of Stardawg.',
  },
  {
    key: 'stardawg',
    name: 'Stardawg',
    breeder: 'Top Dawg Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Pinene', 'Limonene'],
    cannabinoids: 'THC 20-28%',
    origin: 'Chemdawg 4 x Tres Dawg',
    notes: 'Sparkly, chem-and-pine hybrid that became a UK and US staple.',
  },

  // ---- Cookies / dessert expansion ----
  {
    key: 'snowman',
    name: 'Snowman',
    breeder: 'Cookies',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 22-28%',
    origin: 'GSC phenotype',
    notes: 'Sweet vanilla-cookie GSC cut; a parent of Gary Payton and Cereal Milk.',
  },
  {
    key: 'the-y',
    name: 'The Y (Yampa)',
    breeder: 'Cookies',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Cookies family selection',
    notes: 'Cookies-line cut used as a parent of Gary Payton.',
  },
  {
    key: 'gary-payton',
    name: 'Gary Payton',
    breeder: 'Cookies / Powerzzzup',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 22-28%',
    origin: 'The Y x Snowman',
    notes: 'Cool, gassy-sweet hype strain that defined the modern Cookies wave.',
  },
  {
    key: 'starfighter',
    name: 'Starfighter',
    breeder: 'Alien Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Alien Tahoe OG x Lemon Alien Dawg',
    notes: 'Resinous alien-line hybrid; a parent of Cookies and Cream and MAC.',
  },
  {
    key: 'cookies-and-cream',
    name: 'Cookies and Cream',
    breeder: 'Exotic Genetix',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Starfighter x GSC',
    notes: 'Sweet, nutty, vanilla cookie hybrid; a parent of Oreoz.',
  },
  {
    key: 'sinmint-cookies',
    name: 'SinMint Cookies',
    breeder: 'Sin City Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 20-26%',
    origin: 'GSC x Blue Power',
    notes: 'Minty, frosty Cookies cross; the other parent of Animal Mints.',
  },
  {
    key: 'kush-mints',
    name: 'Kush Mints',
    breeder: 'Seed Junky Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 22-28%',
    origin: 'Bubba Kush x Animal Mints',
    notes: 'Minty, cookie-kush hybrid; a parent of many modern dessert strains.',
  },
  {
    key: 'biscotti',
    name: 'Biscotti',
    breeder: 'Cookies',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 21-25%',
    origin: 'Gelato #25 x South Florida OG',
    notes: 'Sweet cookie-and-gas indica; a parent of Permanent Marker.',
  },
  {
    key: 'mac',
    name: 'MAC (Miracle Alien Cookies)',
    breeder: 'Capulator',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Pinene'],
    cannabinoids: 'THC 21-26%',
    origin: 'Alien Cookies x (Colombian x Starfighter)',
    notes: 'Creamy, citrus-and-diesel hybrid celebrated for its balanced, glossy bag appeal.',
  },
  {
    key: 'white-fire-og',
    name: 'White Fire OG (WiFi)',
    breeder: 'OG Raskal',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-28%',
    origin: 'Fire OG x The White',
    notes: 'Frosty, gassy hybrid; a parent of Jungle Cake.',
  },
  {
    key: 'the-white',
    name: 'The White',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Unknown clone-only',
    notes: 'Nearly odorless cut coated in white trichomes; a key resin parent.',
  },
  {
    key: 'jungle-cake',
    name: 'Jungle Cake',
    breeder: 'Tiki Madman / Seed Junky',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Wedding Cake x White Fire OG',
    notes: 'Sweet, gassy, very frosty hybrid with high resin production.',
  },
  {
    key: 'london-pound-cake',
    name: 'London Pound Cake',
    breeder: 'Cookies',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 22-29%',
    origin: 'Sunset Sherbet x ...',
    notes: 'Berry-grape, lemony Cookies indica with a relaxing finish.',
  },
  {
    key: 'georgia-pie',
    name: 'Georgia Pie',
    breeder: 'SeedJunky',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Gelatti x Kush Mints',
    notes: 'Sweet peach-cobbler hybrid with a creamy, dessert-like profile.',
  },
  {
    key: 'jealousy',
    name: 'Jealousy',
    breeder: 'Seed Junky / Minntz',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 22-29%',
    origin: 'Gelato #41 x Sherbert Bx1',
    notes: 'Creamy, funky hybrid named Leafly Strain of the Year 2022; parent of Permanent Marker.',
  },
  {
    key: 'gelato-41',
    name: 'Gelato #41',
    breeder: 'Cookie Fam',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Gelato phenotype',
    notes: 'Gassy, dessert-sweet Gelato cut; a parent of Gushers and Jealousy.',
  },
  {
    key: 'mochi',
    name: 'Mochi (Gelato #47)',
    breeder: 'Sherbinski',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 21-27%',
    origin: 'Sunset Sherbet x Thin Mint GSC',
    notes: 'Minty, fruity Gelato selection with a smooth, relaxing balance.',
  },
  {
    key: 'cereal-milk',
    name: 'Cereal Milk',
    breeder: 'Cookies / Powerzzzup',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Y Life x Snowman',
    notes: 'Sweet, creamy, ice-cream-like Cookies hybrid with a mellow effect.',
  },
  {
    key: 'platinum-gsc',
    name: 'Platinum GSC',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-27%',
    origin: 'GSC phenotype',
    notes: 'Extra-frosty Cookies cut with a sweet, berry-spice profile.',
  },
  {
    key: 'permanent-marker',
    name: 'Permanent Marker',
    breeder: 'Seed Junky Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 24-30%',
    origin: 'Biscotti x Jealousy x Sherb Bx',
    notes: 'Soapy-floral, gassy hybrid named Leafly Strain of the Year 2023.',
  },
  {
    key: 'pink-panties',
    name: 'Pink Panties',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 18-23%',
    origin: 'Burmese Kush family selection',
    notes: 'Sweet, floral indica cut; the other parent of Sunset Sherbet.',
  },

  // ---- Runtz / exotic dessert expansion ----
  {
    key: 'white-runtz',
    name: 'White Runtz',
    breeder: 'Runtz Crew',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 22-29%',
    origin: 'Runtz phenotype',
    notes: 'Frosty, candy-sweet Runtz cut coated in white trichomes.',
  },
  {
    key: 'pink-runtz',
    name: 'Pink Runtz',
    breeder: 'Runtz Crew',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 21-27%',
    origin: 'Runtz phenotype',
    notes: 'Sweet, fruity-candy Runtz selection with a balanced, happy effect.',
  },
  {
    key: 'gushers',
    name: 'Gushers (White Gushers)',
    breeder: 'Cookies',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-25%',
    origin: 'Gelato #41 x Triangle Kush',
    notes: 'Sweet tropical-fruit-and-cream hybrid with a heavy, relaxing tail.',
  },
  {
    key: 'sour-apple',
    name: 'Sour Apple',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Sour Diesel x Cinderella 99',
    notes: 'Tart green-apple-and-diesel hybrid; a parent of Apple Fritter.',
  },
  {
    key: 'apple-fritter',
    name: 'Apple Fritter',
    breeder: 'Lumpy\u2019s Flowers',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Sour Apple x Animal Cookies',
    notes: 'Sweet, pastry-like hybrid repeatedly listed among the strongest strains.',
  },
  {
    key: 'ice-cream-cake',
    name: 'Ice Cream Cake',
    breeder: 'Seed Junky Genetics',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 22-27%',
    origin: 'Wedding Cake x Gelato #33',
    notes: 'Creamy, vanilla-sweet indica with a soothing, sedating effect.',
  },
  {
    key: 'wedding-crasher',
    name: 'Wedding Crasher',
    breeder: 'Symbiotic Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Wedding Cake x Purple Punch',
    notes: 'Sweet vanilla-grape sativa-leaning hybrid with bright, happy effects.',
  },
  {
    key: 'mimosa',
    name: 'Mimosa',
    breeder: 'Symbiotic Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 19-27%',
    origin: 'Clementine x Purple Punch',
    notes: 'Bright citrus daytime hybrid that became a modern dispensary favourite.',
  },
  {
    key: 'clementine',
    name: 'Clementine',
    breeder: 'Crockett Family Farms',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Terpinolene', 'Myrcene'],
    cannabinoids: 'THC 19-27%',
    origin: 'Tangie x Lemon Skunk',
    notes: 'Intense orange-citrus sativa; a parent of Mimosa.',
  },
  {
    key: 'tangie',
    name: 'Tangie',
    breeder: 'DNA Genetics',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Myrcene', 'Pinene'],
    cannabinoids: 'THC 19-22%',
    origin: 'California Orange x Skunk #1',
    notes: 'Tangerine-forward sativa revival; a parent of Clementine and Tropicana Cookies.',
  },
  {
    key: 'lemon-cherry-gelato',
    name: 'Lemon Cherry Gelato',
    breeder: 'Backpackboyz',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Linalool'],
    cannabinoids: 'THC 22-28%',
    origin: 'Sunset Sherbet x GSC',
    notes: 'Sweet cherry-citrus exotic that became one of the most hyped recent strains.',
  },
  {
    key: 'oreoz',
    name: 'Oreoz',
    breeder: '3rd Coast Genetics',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 23-30%',
    origin: 'Cookies and Cream x Secret Weapon',
    notes: 'Chocolate-and-diesel indica known for extreme potency and bag appeal.',
  },

  // ---- Haze / sativa expansion ----
  {
    key: 'amnesia-haze',
    name: 'Amnesia Haze',
    breeder: 'Soma / Dutch',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Limonene', 'Myrcene'],
    cannabinoids: 'THC 20-25%',
    origin: 'Haze x Afghani/Hawaiian lineage',
    notes: 'Energetic, citrus-spice Haze and a perennial Cannabis Cup contender.',
  },
  {
    key: 'lemon-skunk',
    name: 'Lemon Skunk',
    breeder: 'DNA Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Myrcene'],
    cannabinoids: 'THC 17-22%',
    origin: 'Skunk #1 phenotype',
    notes: 'Zesty lemon Skunk selection; a parent of Super Lemon Haze and Clementine.',
  },
  {
    key: 'super-lemon-haze',
    name: 'Super Lemon Haze',
    breeder: 'Green House Seeds',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Terpinolene', 'Caryophyllene'],
    cannabinoids: 'THC 19-25%',
    origin: 'Lemon Skunk x Super Silver Haze',
    notes: 'Two-time Cannabis Cup winner; bright lemon-candy sativa.',
  },
  {
    key: 'ghost-train-haze',
    name: 'Ghost Train Haze',
    breeder: 'Rare Dankness',
    type: 'Sativa',
    floweringWeeks: 11,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 22-28%',
    origin: 'Ghost OG x Neville\u2019s Wreck',
    notes: 'Intensely potent citrus-floral sativa once crowned strongest in the US.',
  },
  {
    key: 'c99',
    name: 'Cinderella 99',
    breeder: 'Brothers Grimm',
    type: 'Sativa',
    floweringWeeks: 8,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Terpinolene', 'Pinene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Jack Herer x Shiva Skunk',
    notes: 'Fast, pineapple-citrus sativa (a.k.a. C99); a parent of Sour Apple.',
  },
  {
    key: 'chocolope',
    name: 'Chocolope',
    breeder: 'DNA Genetics',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Chocolate Thai x Cannalope Haze',
    notes: 'Coffee-and-melon sativa that revived the Chocolate Thai flavour.',
  },
  {
    key: 'maui-wowie',
    name: 'Maui Wowie',
    breeder: 'Heirloom',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Pinene'],
    cannabinoids: 'THC 13-19%',
    origin: 'Hawaiian landrace',
    notes: 'Classic tropical-pineapple Hawaiian sativa with a light, breezy high.',
  },
  {
    key: 'candyland',
    name: 'Candyland',
    breeder: 'Ken Estes',
    type: 'Sativa',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 19-24%',
    origin: 'Granddaddy Purple x Bay Platinum Cookies',
    notes: 'Sweet, spicy sativa-leaning hybrid and a Cannabis Cup winner.',
  },
  {
    key: 'silver-haze',
    name: 'Silver Haze',
    breeder: 'Sensi Seeds',
    type: 'Sativa',
    floweringWeeks: 10,
    stretch: 'High',
    terpeneProfile: ['Terpinolene', 'Myrcene'],
    cannabinoids: 'THC 18-23%',
    origin: 'Haze x Northern Lights',
    notes: 'The resinous Haze x NL bridge behind the entire Silver Haze line.',
  },

  // ---- Blueberry / Cheese / fruit expansion ----
  {
    key: 'cheese',
    name: 'Cheese',
    breeder: 'Exodus (UK)',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Skunk #1 phenotype',
    notes: 'Pungent, tangy UK clone-only classic; a parent of Blue Cheese.',
  },
  {
    key: 'blue-cheese',
    name: 'Blue Cheese',
    breeder: 'Big Buddha Seeds',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 15-20%',
    origin: 'Blueberry x Cheese',
    notes: 'Savory-sweet indica blending blueberry sweetness with funky Cheese.',
  },
  {
    key: 'flo',
    name: 'Flo',
    breeder: 'DJ Short',
    type: 'Hybrid',
    floweringWeeks: 8,
    stretch: 'Medium',
    terpeneProfile: ['Pinene', 'Myrcene'],
    cannabinoids: 'THC 16-21%',
    origin: 'Purple Thai x Afghani',
    notes: 'DJ Short classic with a clear, floral-fruity, easy-going high.',
  },
  {
    key: 'blackberry-kush',
    name: 'Blackberry Kush',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Linalool'],
    cannabinoids: 'THC 16-20%',
    origin: 'Afghani x Blackberry',
    notes: 'Sweet berry-and-fuel indica with a heavy, relaxing body effect.',
  },
  {
    key: 'blue-cookies',
    name: 'Blue Cookies',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    cannabinoids: 'THC 20-25%',
    origin: 'GSC x Blueberry',
    notes: 'Berry-sweet Cookies cross with vivid colours and a relaxing punch.',
  },

  // ---- Purple / Cherry / fruit-dessert expansion ----
  {
    key: 'mendocino-purps',
    name: 'Mendocino Purps',
    breeder: 'BC Bud Depot',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Pinene'],
    cannabinoids: 'THC 15-21%',
    origin: 'Mendocino County clone-only',
    notes: 'Purple-prone NorCal heirloom; a parent of Grape Ape and Purple Urkle.',
  },
  {
    key: 'cherry-pie',
    name: 'Cherry Pie',
    breeder: 'Clone-only',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 16-24%',
    origin: 'Granddaddy Purple x Durban Poison',
    notes: 'Sweet-and-sour cherry hybrid; a parent of Grape Pie and Forbidden Fruit.',
  },
  {
    key: 'grape-pie',
    name: 'Grape Pie',
    breeder: 'Cannarado Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-22%',
    origin: 'Cherry Pie x Granddaddy Purple',
    notes: 'Grape-jam dessert hybrid; a parent of Sundae Driver and Lava Cake.',
  },
  {
    key: 'forbidden-fruit',
    name: 'Forbidden Fruit',
    breeder: 'Clone-only',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 18-24%',
    origin: 'Cherry Pie x Tangie',
    notes: 'Tropical cherry-citrus indica with a rich, resinous, relaxing profile.',
  },
  {
    key: 'sundae-driver',
    name: 'Sundae Driver',
    breeder: 'Cannarado Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Linalool'],
    cannabinoids: 'THC 18-24%',
    origin: 'Fruity Pebbles OG x Grape Pie',
    notes: 'Creamy, fruity, smooth hybrid with a calm and balanced effect.',
  },
  {
    key: 'fpog',
    name: 'Fruity Pebbles OG',
    breeder: 'Alien Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 18-25%',
    origin: 'Granddaddy Purple x Tahoe OG x ...',
    notes: 'Sweet cereal-and-berry hybrid (a.k.a. FPOG); a parent of Sundae Driver.',
  },
  {
    key: 'lava-cake',
    name: 'Lava Cake',
    breeder: 'Cannarado Genetics',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    cannabinoids: 'THC 20-25%',
    origin: 'Thin Mint GSC x Grape Pie',
    notes: 'Chocolate-mint-and-berry indica with a rich, relaxing finish.',
  },
  {
    key: 'wedding-pie',
    name: 'Wedding Pie',
    breeder: 'Cannarado Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene'],
    cannabinoids: 'THC 20-26%',
    origin: 'Wedding Cake x Grape Pie',
    notes: 'Gassy, tangy dessert hybrid blending two modern dessert heavyweights.',
  },
  {
    key: 'tropicana-cookies',
    name: 'Tropicana Cookies',
    breeder: 'Oni Seed Co',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'High',
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Myrcene'],
    cannabinoids: 'THC 20-28%',
    origin: 'GSC x Tangie',
    notes: 'Vivid orange-citrus Cookies sativa with bright, uplifting effects.',
  },
  {
    key: 'orange-cookies',
    name: 'Orange Cookies',
    breeder: 'Franchise Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Limonene', 'Caryophyllene'],
    cannabinoids: 'THC 18-24%',
    origin: 'Orange Juice x GSC',
    notes: 'Sweet orange-cream Cookies hybrid with a happy, relaxed effect.',
  },
  {
    key: 'peanut-butter-breath',
    name: 'Peanut Butter Breath',
    breeder: 'ThugPug Genetics',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Humulene'],
    cannabinoids: 'THC 18-26%',
    origin: 'Do-Si-Dos x Mendo Breath',
    notes: 'Nutty, earthy hybrid known for a deeply relaxing, sedating effect.',
  },

  // ---- White / Widow line ----
  {
    key: 'white-rhino',
    name: 'White Rhino',
    breeder: 'Green House Seeds',
    type: 'Indica',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Caryophyllene'],
    cannabinoids: 'THC 18-23%',
    origin: 'White Widow x North American Indica',
    notes: 'Heavy, frosty White Widow descendant with strong body relaxation.',
  },

  // ---- CBD / autoflower line ----
  {
    key: 'lowryder',
    name: 'Lowryder',
    breeder: 'The Joint Doctor',
    type: 'Indica',
    floweringWeeks: 8,
    stretch: 'Low',
    terpeneProfile: ['Myrcene', 'Pinene'],
    cannabinoids: 'THC 12-16%',
    origin: 'Williams Wonder x Northern Lights x Ruderalis',
    notes: 'The first commercial autoflower; ancestor of nearly all modern autos.',
  },
  {
    key: 'cannatonic',
    name: 'Cannatonic',
    breeder: 'Resin Seeds',
    type: 'Hybrid',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC 6-12% / CBD 6-17%',
    origin: 'MK Ultra x G13 Haze',
    notes: 'Landmark high-CBD strain; a parent of the famous ACDC pheno.',
  },
  {
    key: 'acdc',
    name: 'ACDC',
    breeder: 'Clone-only',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Pinene'],
    cannabinoids: 'THC 1-6% / CBD 14-20%',
    origin: 'Cannatonic phenotype',
    notes: 'Very high-CBD, low-THC cut popular for clear-headed therapeutic use.',
  },
  {
    key: 'harlequin',
    name: 'Harlequin',
    breeder: 'Clone-only',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Pinene'],
    cannabinoids: 'THC 5-10% / CBD 8-16%',
    origin: 'Colombian Gold x Thai x Swiss landrace lineage',
    notes: 'Reliable balanced-CBD sativa with a gentle, functional effect.',
  },
  {
    key: 'charlottes-web',
    name: 'Charlotte\u2019s Web',
    breeder: 'Stanley Brothers',
    type: 'Sativa',
    floweringWeeks: 9,
    stretch: 'Medium',
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    cannabinoids: 'THC <1% / CBD 13-20%',
    origin: 'Industrial hemp selection',
    notes: 'The high-CBD hemp variety that brought medical CBD into the mainstream.',
  },
];

export const CURATED_GENETICS: Genetics[] = CURATED_GENETICS_INPUT.map(buildGenetics);

export const CURATED_LINEAGE_EDGES: LineageEdge[] = [
  // Skunk #1 and friends
  buildEdge('afghani', 'skunk-1'),
  buildEdge('acapulco-gold', 'skunk-1'),
  buildEdge('colombian-gold', 'skunk-1'),
  buildEdge('afghani', 'northern-lights'),
  buildEdge('thai', 'northern-lights'),
  buildEdge('skunk-1', 'super-skunk'),
  buildEdge('afghani', 'super-skunk'),
  buildEdge('northern-lights', 'shiva-skunk'),
  buildEdge('skunk-1', 'shiva-skunk'),
  buildEdge('northern-lights', 'big-bud'),
  buildEdge('skunk-1', 'big-bud'),
  buildEdge('afghani', 'big-bud'),
  buildEdge('skunk-1', 'green-crack'),

  // Haze family
  buildEdge('haze', 'super-silver-haze'),
  buildEdge('northern-lights', 'super-silver-haze'),
  buildEdge('skunk-1', 'super-silver-haze'),
  buildEdge('haze', 'jack-herer'),
  buildEdge('northern-lights', 'jack-herer'),
  buildEdge('shiva-skunk', 'jack-herer'),
  buildEdge('blueberry', 'blue-dream'),
  buildEdge('haze', 'blue-dream'),

  // Chem / Diesel / OG family
  buildEdge('chemdawg', 'og-kush'),
  buildEdge('hindu-kush', 'og-kush'),
  buildEdge('chemdawg', 'sour-diesel'),
  buildEdge('super-skunk', 'sour-diesel'),
  buildEdge('chemdawg', 'chems-sister'),
  buildEdge('sour-diesel', 'sour-dubble'),
  buildEdge('sour-diesel', 'chocolate-diesel'),
  buildEdge('chems-sister', 'original-glue'),
  buildEdge('sour-dubble', 'original-glue'),
  buildEdge('chocolate-diesel', 'original-glue'),
  buildEdge('og-kush', 'triangle-kush'),
  buildEdge('og-kush', 'face-off-og'),
  buildEdge('og-kush', 'bubba-kush'),
  buildEdge('og-kush', 'bruce-banner'),
  buildEdge('og-kush', 'larry-og'),

  // Cookies / dessert family
  buildEdge('og-kush', 'gsc'),
  buildEdge('durban-poison', 'gsc'),
  buildEdge('gsc', 'thin-mint-gsc'),
  buildEdge('gsc', 'animal-cookies'),
  buildEdge('animal-cookies', 'animal-mints'),
  buildEdge('gsc', 'sunset-sherbet'),
  buildEdge('sunset-sherbet', 'gelato'),
  buildEdge('thin-mint-gsc', 'gelato'),
  buildEdge('gelato', 'gelato-33'),
  buildEdge('triangle-kush', 'wedding-cake'),
  buildEdge('animal-mints', 'wedding-cake'),
  buildEdge('gsc', 'do-si-dos'),
  buildEdge('face-off-og', 'do-si-dos'),

  // Zkittlez / Runtz / fruit family
  buildEdge('afghani', 'grape-ape'),
  buildEdge('skunk-1', 'grape-ape'),
  buildEdge('grape-ape', 'zkittlez'),
  buildEdge('grapefruit', 'zkittlez'),
  buildEdge('zkittlez', 'runtz'),
  buildEdge('gelato', 'runtz'),

  // Purple family
  buildEdge('purple-urkle', 'granddaddy-purple'),
  buildEdge('big-bud', 'granddaddy-purple'),
  buildEdge('larry-og', 'purple-punch'),
  buildEdge('granddaddy-purple', 'purple-punch'),

  // Sativa hybrids
  buildEdge('thai', 'trainwreck'),
  buildEdge('afghani', 'trainwreck'),
  buildEdge('trainwreck', 'pineapple-express'),
  buildEdge('hawaiian', 'pineapple-express'),
  buildEdge('colombian-gold', 'ak-47'),
  buildEdge('thai', 'ak-47'),
  buildEdge('afghani', 'ak-47'),

  // ---- Corrections / additional parents for existing nodes ----
  buildEdge('purple-thai', 'blueberry'),
  buildEdge('afghani', 'blueberry'),
  buildEdge('chocolate-thai', 'chocolate-diesel'),
  buildEdge('mexican', 'haze'),
  buildEdge('mexican', 'trainwreck'),
  buildEdge('mexican', 'ak-47'),
  buildEdge('sfv-og', 'larry-og'),
  buildEdge('fire-og', 'animal-cookies'),
  buildEdge('mendocino-purps', 'grape-ape'),
  buildEdge('mendocino-purps', 'purple-urkle'),
  buildEdge('pink-panties', 'sunset-sherbet'),
  buildEdge('strawberry-diesel', 'bruce-banner'),
  buildEdge('sinmint-cookies', 'animal-mints'),

  // ---- OG / Kush dynasty ----
  buildEdge('og-kush', 'sfv-og'),
  buildEdge('og-kush', 'fire-og'),
  buildEdge('sfv-og', 'fire-og'),
  buildEdge('og-kush', 'tahoe-og'),
  buildEdge('sfv-og', 'tahoe-og'),
  buildEdge('og-kush', 'ghost-og'),
  buildEdge('mazar', 'skywalker'),
  buildEdge('blueberry', 'skywalker'),
  buildEdge('skywalker', 'skywalker-og'),
  buildEdge('og-kush', 'skywalker-og'),
  buildEdge('og-kush', 'headband'),
  buildEdge('sour-diesel', 'headband'),
  buildEdge('chemdawg', 'gmo'),
  buildEdge('gsc', 'gmo'),
  buildEdge('hindu-kush', 'master-kush'),
  buildEdge('skunk-1', 'master-kush'),
  buildEdge('tahoe-og', 'alien-og'),
  buildEdge('og-kush', 'king-louis'),
  buildEdge('og-kush', 'khalifa-kush'),
  buildEdge('og-kush', 'platinum-og'),
  buildEdge('master-kush', 'platinum-og'),
  buildEdge('g13', 'mk-ultra'),
  buildEdge('og-kush', 'mk-ultra'),
  buildEdge('g13', 'g13-haze'),
  buildEdge('haze', 'g13-haze'),
  buildEdge('og-kush', 'kosher-kush'),
  buildEdge('og-kush', 'mendo-breath'),
  buildEdge('ghost-og', 'banana-kush'),
  buildEdge('og-kush', 'banana-og'),

  // ---- Diesel / Chem ----
  buildEdge('mexican', 'nyc-diesel'),
  buildEdge('afghani', 'nyc-diesel'),
  buildEdge('haze', 'strawberry-cough'),
  buildEdge('strawberry-cough', 'strawberry-diesel'),
  buildEdge('nyc-diesel', 'strawberry-diesel'),
  buildEdge('chemdawg', 'tres-dawg'),
  buildEdge('afghani', 'tres-dawg'),
  buildEdge('chemdawg', 'stardawg'),
  buildEdge('tres-dawg', 'stardawg'),

  // ---- Cookies / dessert ----
  buildEdge('gsc', 'snowman'),
  buildEdge('the-y', 'gary-payton'),
  buildEdge('snowman', 'gary-payton'),
  buildEdge('starfighter', 'cookies-and-cream'),
  buildEdge('gsc', 'cookies-and-cream'),
  buildEdge('gsc', 'sinmint-cookies'),
  buildEdge('bubba-kush', 'kush-mints'),
  buildEdge('animal-mints', 'kush-mints'),
  buildEdge('gelato', 'biscotti'),
  buildEdge('starfighter', 'mac'),
  buildEdge('fire-og', 'white-fire-og'),
  buildEdge('the-white', 'white-fire-og'),
  buildEdge('wedding-cake', 'jungle-cake'),
  buildEdge('white-fire-og', 'jungle-cake'),
  buildEdge('sunset-sherbet', 'london-pound-cake'),
  buildEdge('kush-mints', 'georgia-pie'),
  buildEdge('gelato', 'gelato-41'),
  buildEdge('gelato-41', 'jealousy'),
  buildEdge('sunset-sherbet', 'mochi'),
  buildEdge('thin-mint-gsc', 'mochi'),
  buildEdge('snowman', 'cereal-milk'),
  buildEdge('gsc', 'platinum-gsc'),
  buildEdge('biscotti', 'permanent-marker'),
  buildEdge('jealousy', 'permanent-marker'),

  // ---- Runtz / exotic dessert ----
  buildEdge('runtz', 'white-runtz'),
  buildEdge('runtz', 'pink-runtz'),
  buildEdge('gelato-41', 'gushers'),
  buildEdge('triangle-kush', 'gushers'),
  buildEdge('sour-diesel', 'sour-apple'),
  buildEdge('c99', 'sour-apple'),
  buildEdge('sour-apple', 'apple-fritter'),
  buildEdge('animal-cookies', 'apple-fritter'),
  buildEdge('wedding-cake', 'ice-cream-cake'),
  buildEdge('gelato-33', 'ice-cream-cake'),
  buildEdge('wedding-cake', 'wedding-crasher'),
  buildEdge('purple-punch', 'wedding-crasher'),
  buildEdge('clementine', 'mimosa'),
  buildEdge('purple-punch', 'mimosa'),
  buildEdge('tangie', 'clementine'),
  buildEdge('lemon-skunk', 'clementine'),
  buildEdge('california-orange', 'tangie'),
  buildEdge('skunk-1', 'tangie'),
  buildEdge('sunset-sherbet', 'lemon-cherry-gelato'),
  buildEdge('gsc', 'lemon-cherry-gelato'),
  buildEdge('cookies-and-cream', 'oreoz'),

  // ---- Haze / sativa ----
  buildEdge('haze', 'amnesia-haze'),
  buildEdge('skunk-1', 'lemon-skunk'),
  buildEdge('lemon-skunk', 'super-lemon-haze'),
  buildEdge('super-silver-haze', 'super-lemon-haze'),
  buildEdge('ghost-og', 'ghost-train-haze'),
  buildEdge('jack-herer', 'c99'),
  buildEdge('shiva-skunk', 'c99'),
  buildEdge('chocolate-thai', 'chocolope'),
  buildEdge('cannalope-haze', 'chocolope'),
  buildEdge('hawaiian', 'maui-wowie'),
  buildEdge('granddaddy-purple', 'candyland'),
  buildEdge('haze', 'silver-haze'),
  buildEdge('northern-lights', 'silver-haze'),

  // ---- Blueberry / Cheese / fruit ----
  buildEdge('skunk-1', 'cheese'),
  buildEdge('blueberry', 'blue-cheese'),
  buildEdge('cheese', 'blue-cheese'),
  buildEdge('purple-thai', 'flo'),
  buildEdge('afghani', 'flo'),
  buildEdge('afghani', 'blackberry-kush'),
  buildEdge('gsc', 'blue-cookies'),
  buildEdge('blueberry', 'blue-cookies'),

  // ---- Purple / Cherry / fruit-dessert ----
  buildEdge('granddaddy-purple', 'cherry-pie'),
  buildEdge('durban-poison', 'cherry-pie'),
  buildEdge('cherry-pie', 'grape-pie'),
  buildEdge('granddaddy-purple', 'grape-pie'),
  buildEdge('cherry-pie', 'forbidden-fruit'),
  buildEdge('tangie', 'forbidden-fruit'),
  buildEdge('grape-pie', 'sundae-driver'),
  buildEdge('fpog', 'sundae-driver'),
  buildEdge('granddaddy-purple', 'fpog'),
  buildEdge('tahoe-og', 'fpog'),
  buildEdge('thin-mint-gsc', 'lava-cake'),
  buildEdge('grape-pie', 'lava-cake'),
  buildEdge('wedding-cake', 'wedding-pie'),
  buildEdge('grape-pie', 'wedding-pie'),
  buildEdge('gsc', 'tropicana-cookies'),
  buildEdge('tangie', 'tropicana-cookies'),
  buildEdge('gsc', 'orange-cookies'),
  buildEdge('do-si-dos', 'peanut-butter-breath'),
  buildEdge('mendo-breath', 'peanut-butter-breath'),

  // ---- White / Widow line ----
  buildEdge('white-widow', 'white-rhino'),

  // ---- CBD / autoflower line ----
  buildEdge('northern-lights', 'lowryder'),
  buildEdge('ruderalis', 'lowryder'),
  buildEdge('mk-ultra', 'cannatonic'),
  buildEdge('g13-haze', 'cannatonic'),
  buildEdge('cannatonic', 'acdc'),
  buildEdge('colombian-gold', 'harlequin'),
];
